# A Catppuccin RC file to element. In beta, specs may change. 
app_name: element
binary_name: element-desktop 
installation:
  location: 
    macos: ~/.config/Element/
    linux: ~/.config/Element/
    windows: "%appdata%/Element"
  flavours: 
    all:
      default: 
        - config.json
  to: .
  one_flavour: false 
  comments: "To enable the themes, please go to your App settings => Labs and enable 'Support adding custom themes'. Then go to Appearance tab and select the theme."

